In [1]:
import os
import numpy as np
import torch
from torchvision import datasets
from torch.utils.data import Dataset
import copy

/usr/local/home/sgchr/anaconda3/envs/pyt/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /usr/local/home/sgchr/anaconda3/envs/pyt/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")


In [2]:
def get_CIFAR10(path):
    data_tr = datasets.CIFAR10(path + '/CIFAR10', train=True, download=True)
    data_te = datasets.CIFAR10(path + '/CIFAR10', train=False, download=True)
    X_tr = data_tr.data
    Y_tr = torch.from_numpy(np.array(data_tr.targets))
    X_te = data_te.data
    Y_te = torch.from_numpy(np.array(data_te.targets))
    return X_tr, Y_tr, X_te, Y_te

In [3]:
X_tr, Y_tr, X_te, Y_te = get_CIFAR10('data')

Files already downloaded and verified
Files already downloaded and verified


In [4]:
def decrease_dataset(X_tr, Y_tr):
    new_size = 50
    masks = [np.zeros(len(Y_tr), dtype = 'int') for i in range(10)]
    for i in range(len(Y_tr)):
        masks[Y_tr[i].item()][i] = 1

    # creating new_Xtr
    new_Xtr = []
    for i in masks:
        var = np.random.choice(np.arange(len(X_tr), dtype=int)[i == 1], int(new_size/10), replace=False)
        new_Xtr.append(X_tr[var])

    new_Xtr = np.array(new_Xtr).reshape(new_size, 32, 32, 3)

    # creating new_Ytr
    new_Ytr = np.zeros(new_size, dtype = 'int')
    slce = int(new_size/10)
    for i in range(10):
        new_Ytr[int(slce-new_size/10):slce] = i
        slce += int(new_size/10)
    return new_Xtr, torch.from_numpy(new_Ytr)

In [5]:
new_Xtr, new_Ytr = decrease_dataset(X_tr, Y_tr)

In [6]:
def relabel(new_Xtr, new_Size = 10):
    img_per_cls = new_Size/10
    class_to_swap = 3
    long = int(img_per_cls * class_to_swap)
    temp = copy.deepcopy(new_Xtr[long:int(long +5)])
    cls_to_swp_with = 7
    long_two = int(img_per_cls * cls_to_swp_with)
    new_Xtr[long:int(long +5)] = copy.deepcopy(new_Xtr[long_two : int(long_two+5)])
    new_Xtr[long_two : int(long_two+5)] = temp
    return new_Xtr

In [7]:
a = np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [8]:
c = relabel(new_Xtr)

In [9]:
c

array([[[[194, 199, 202],
         [198, 203, 206],
         [202, 207, 210],
         ...,
         [190, 195, 198],
         [186, 191, 194],
         [182, 187, 190]],

        [[194, 199, 202],
         [198, 203, 206],
         [202, 207, 210],
         ...,
         [191, 196, 199],
         [186, 191, 194],
         [182, 187, 190]],

        [[195, 200, 203],
         [199, 204, 207],
         [202, 207, 210],
         ...,
         [191, 196, 199],
         [187, 192, 195],
         [184, 189, 192]],

        ...,

        [[197, 204, 206],
         [201, 207, 210],
         [204, 211, 213],
         ...,
         [201, 209, 211],
         [198, 206, 208],
         [196, 203, 205]],

        [[197, 202, 205],
         [200, 205, 208],
         [204, 209, 212],
         ...,
         [201, 209, 211],
         [198, 206, 208],
         [195, 202, 204]],

        [[194, 202, 202],
         [198, 205, 206],
         [201, 208, 209],
         ...,
         [201, 209, 211],
        

In [10]:
new_Xtr[15]

array([[[ 62,  76,  67],
        [ 61,  82,  67],
        [ 65,  93,  72],
        ...,
        [249, 250, 245],
        [249, 250, 245],
        [251, 252, 247]],

       [[ 64,  74,  72],
        [ 60,  77,  66],
        [ 59,  84,  64],
        ...,
        [247, 248, 243],
        [247, 248, 243],
        [249, 250, 245]],

       [[ 67,  73,  78],
        [ 61,  76,  68],
        [ 61,  83,  64],
        ...,
        [249, 250, 245],
        [249, 250, 245],
        [250, 251, 246]],

       ...,

       [[160, 160, 160],
        [177, 176, 177],
        [196, 196, 196],
        ...,
        [ 93,  73,  66],
        [ 92,  73,  66],
        [101,  86,  77]],

       [[244, 244, 244],
        [244, 244, 244],
        [246, 246, 246],
        ...,
        [ 92,  73,  65],
        [ 94,  77,  69],
        [116, 103,  94]],

       [[251, 251, 251],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [ 93,  77,  68],
        [110,  96,  87],
        [144, 135, 124]]

In [11]:
c[15]

array([[[ 62,  76,  67],
        [ 61,  82,  67],
        [ 65,  93,  72],
        ...,
        [249, 250, 245],
        [249, 250, 245],
        [251, 252, 247]],

       [[ 64,  74,  72],
        [ 60,  77,  66],
        [ 59,  84,  64],
        ...,
        [247, 248, 243],
        [247, 248, 243],
        [249, 250, 245]],

       [[ 67,  73,  78],
        [ 61,  76,  68],
        [ 61,  83,  64],
        ...,
        [249, 250, 245],
        [249, 250, 245],
        [250, 251, 246]],

       ...,

       [[160, 160, 160],
        [177, 176, 177],
        [196, 196, 196],
        ...,
        [ 93,  73,  66],
        [ 92,  73,  66],
        [101,  86,  77]],

       [[244, 244, 244],
        [244, 244, 244],
        [246, 246, 246],
        ...,
        [ 92,  73,  65],
        [ 94,  77,  69],
        [116, 103,  94]],

       [[251, 251, 251],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [ 93,  77,  68],
        [110,  96,  87],
        [144, 135, 124]]

In [12]:
a[7 * 5 : 7 * 6]

array([35, 36, 37, 38, 39, 40, 41])

In [13]:
x= np.arange(5)
y = np.arange(6)
x == y

/tmp/ipykernel_421891/1334500549.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  x == y


False

In [3]:
import logging
total = 10
backwardSteps = 0
K = 1000

logging.basicConfig(level=logging.DEBUG, filename='out.log', filemode='w', format='%(name)s - %(levelname)s - %(message)s')
logging.debug("Average time of chunk loop: " + str(total/(backwardSteps + 1) *  K))