In [11]:
import resnet
model = resnet.ResNet18() 

ModuleNotFoundError: No module named 'resnet'

In [3]:
for name, param in model.named_parameters():
    print(name, param.shape)

conv1.weight torch.Size([16, 3, 3, 3])
bn1.weight torch.Size([16])
bn1.bias torch.Size([16])
layer1.0.conv1.weight torch.Size([16, 16, 3, 3])
layer1.0.bn1.weight torch.Size([16])
layer1.0.bn1.bias torch.Size([16])
layer1.0.conv2.weight torch.Size([16, 16, 3, 3])
layer1.0.bn2.weight torch.Size([16])
layer1.0.bn2.bias torch.Size([16])
layer1.1.conv1.weight torch.Size([16, 16, 3, 3])
layer1.1.bn1.weight torch.Size([16])
layer1.1.bn1.bias torch.Size([16])
layer1.1.conv2.weight torch.Size([16, 16, 3, 3])
layer1.1.bn2.weight torch.Size([16])
layer1.1.bn2.bias torch.Size([16])
layer2.0.conv1.weight torch.Size([32, 16, 3, 3])
layer2.0.bn1.weight torch.Size([32])
layer2.0.bn1.bias torch.Size([32])
layer2.0.conv2.weight torch.Size([32, 32, 3, 3])
layer2.0.bn2.weight torch.Size([32])
layer2.0.bn2.bias torch.Size([32])
layer2.0.shortcut.0.weight torch.Size([32, 16, 1, 1])
layer2.0.shortcut.1.weight torch.Size([32])
layer2.0.shortcut.1.bias torch.Size([32])
layer2.1.conv1.weight torch.Size([32, 32,

In [30]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[[[-5.4195e-02,  1.4138e-01,  1.4400e-01],
          [ 1.6501e-01, -1.5664e-01, -7.2526e-02],
          [ 9.8825e-02,  2.4240e-02,  7.0558e-02]],

         [[ 1.2382e-01, -1.6156e-01,  8.2782e-02],
          [ 1.7205e-01, -4.8541e-02, -5.3282e-02],
          [-1.8885e-01, -5.3832e-02,  2.3102e-02]],

         [[ 1.2511e-01,  6.0402e-03, -1.8578e-01],
          [-1.8553e-01,  8.5042e-02, -6.6871e-02],
          [-4.3011e-02,  8.0395e-02, -6.2255e-02]]],


        [[[ 5.9806e-02, -1.4164e-01,  5.0508e-02],
          [ 7.4109e-02, -1.1668e-01,  1.0005e-01],
          [ 1.3108e-01, -8.1709e-02,  1.2723e-01]],

         [[ 5.9123e-02,  1.4443e-01, -3.1190e-02],
          [ 1.2514e-01,  9.8840e-02,  1.6734e-01],
          [ 2.9794e-02,  1.0078e-01, -7.4370e-02]],

         [[-9.7924e-02, -7.9844e-02, -8.7165e-02],
          [ 4.8933e-02,  3.4999e-02,  5.1600e-02],
          [ 6.7746e-02,  1.0055e-01, -4.2007e-03]]],


        [[[-1.4041e-01, -1.2247e-01, -1.1136

In [1]:
tensor_list = []
for param in model.parameters():
    tensor_list.append(param)

NameError: name 'model' is not defined

In [32]:
tensor_list

[Parameter containing:
 tensor([[[[-5.4195e-02,  1.4138e-01,  1.4400e-01],
           [ 1.6501e-01, -1.5664e-01, -7.2526e-02],
           [ 9.8825e-02,  2.4240e-02,  7.0558e-02]],
 
          [[ 1.2382e-01, -1.6156e-01,  8.2782e-02],
           [ 1.7205e-01, -4.8541e-02, -5.3282e-02],
           [-1.8885e-01, -5.3832e-02,  2.3102e-02]],
 
          [[ 1.2511e-01,  6.0402e-03, -1.8578e-01],
           [-1.8553e-01,  8.5042e-02, -6.6871e-02],
           [-4.3011e-02,  8.0395e-02, -6.2255e-02]]],
 
 
         [[[ 5.9806e-02, -1.4164e-01,  5.0508e-02],
           [ 7.4109e-02, -1.1668e-01,  1.0005e-01],
           [ 1.3108e-01, -8.1709e-02,  1.2723e-01]],
 
          [[ 5.9123e-02,  1.4443e-01, -3.1190e-02],
           [ 1.2514e-01,  9.8840e-02,  1.6734e-01],
           [ 2.9794e-02,  1.0078e-01, -7.4370e-02]],
 
          [[-9.7924e-02, -7.9844e-02, -8.7165e-02],
           [ 4.8933e-02,  3.4999e-02,  5.1600e-02],
           [ 6.7746e-02,  1.0055e-01, -4.2007e-03]]],
 
 
         [[[-1.40

In [36]:
for idx, i in enumerate(tensor_list):
    print(idx, i)

0 Parameter containing:
tensor([[[[-5.4195e-02,  1.4138e-01,  1.4400e-01],
          [ 1.6501e-01, -1.5664e-01, -7.2526e-02],
          [ 9.8825e-02,  2.4240e-02,  7.0558e-02]],

         [[ 1.2382e-01, -1.6156e-01,  8.2782e-02],
          [ 1.7205e-01, -4.8541e-02, -5.3282e-02],
          [-1.8885e-01, -5.3832e-02,  2.3102e-02]],

         [[ 1.2511e-01,  6.0402e-03, -1.8578e-01],
          [-1.8553e-01,  8.5042e-02, -6.6871e-02],
          [-4.3011e-02,  8.0395e-02, -6.2255e-02]]],


        [[[ 5.9806e-02, -1.4164e-01,  5.0508e-02],
          [ 7.4109e-02, -1.1668e-01,  1.0005e-01],
          [ 1.3108e-01, -8.1709e-02,  1.2723e-01]],

         [[ 5.9123e-02,  1.4443e-01, -3.1190e-02],
          [ 1.2514e-01,  9.8840e-02,  1.6734e-01],
          [ 2.9794e-02,  1.0078e-01, -7.4370e-02]],

         [[-9.7924e-02, -7.9844e-02, -8.7165e-02],
          [ 4.8933e-02,  3.4999e-02,  5.1600e-02],
          [ 6.7746e-02,  1.0055e-01, -4.2007e-03]]],


        [[[-1.4041e-01, -1.2247e-01, -1.11

In [43]:
rand_val = []
for idx, i in enumerate(tensor_list):
    rand_val.append(i[torch.floor(torch.rand(1) * len(a)).long()])

In [72]:
rand_val

[tensor([[[[-0.1404, -0.1225, -0.1114],
           [-0.1528, -0.1131, -0.1441],
           [ 0.1237, -0.1613,  0.1757]],
 
          [[ 0.1840,  0.1314,  0.1250],
           [-0.0810,  0.0082,  0.1540],
           [-0.1608, -0.1287,  0.0308]],
 
          [[ 0.1419,  0.1178,  0.1329],
           [-0.1856, -0.1155,  0.0289],
           [-0.0182,  0.1336, -0.1407]]]], grad_fn=<IndexBackward0>),
 tensor([1.], grad_fn=<IndexBackward0>),
 tensor([0.], grad_fn=<IndexBackward0>),
 tensor([[[[ 0.0525,  0.0639,  0.0666],
           [-0.0338,  0.0207, -0.0564],
           [-0.0277,  0.0310,  0.0709]],
 
          [[-0.0792, -0.0712, -0.0640],
           [ 0.0365,  0.0351, -0.0430],
           [-0.0122, -0.0817, -0.0801]],
 
          [[ 0.0785,  0.0451, -0.0028],
           [ 0.0141, -0.0307,  0.0140],
           [ 0.0070, -0.0598, -0.0734]],
 
          [[-0.0804, -0.0025, -0.0643],
           [-0.0063, -0.0009, -0.0700],
           [ 0.0520,  0.0151, -0.0407]],
 
          [[-0.0528, -0.0737, 

In [4]:
import torch

# create two tensors of different sizes
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6, 7, 8])

# concatenate the tensors along a new dimension
c = torch.cat([a.unsqueeze(0), b.unsqueeze(0)], dim=0)




RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 5 for tensor number 1 in the list.

In [ ]:
# generate a random permutation of the concatenated tensor
permutation = torch.randperm(c.numel())

# select the random values from the concatenated tensor


In [ ]:
random_values = c.view(-1)[permutation[:2]]

# split the tensor back into its original parts


In [ ]:
random_value_a, random_value_b = torch.split(random_values, [1, 1])

print(random_value_a)
print(random_value_b)

In [26]:
import torch

# create two tensors of different sizes
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6, 7, 8])

# pick a random value from each tensor
random_value_a = a[torch.floor(torch.rand(1) * len(a)).long()]
random_value_b = b[torch.floor(torch.rand(1) * len(b)).long()]

print(random_value_a)
print(random_value_b)


tensor([2])
tensor([7])
